restaurant_names = ["America's Incredible Pizza Company",
"Anchor Bar",
"Angus Steakhouse",
"Anjappar Chettinad Restaurant",
"Annalakshmi",
"Applebee's",
"Arab Udupi",
"ASK Italian",
"Bahama Breeze",
"Bakers Square",
"Bar Louie Restaurants",
"Baton Rouge",
"Becks Prime",
"Beef O'Brady's",
"Beefeater",
"Belgo",
"Bella Italia",
"Benihana",
"Bennigan's",
"Bertucci's",
"Bickford's",
"Big Boy",
"Bill's",
"BJ's Restaurants",
"Black Angus Steakhouse",
"Black-eyed Pea",
"Bob Evans Restaurants",
"Bob's Big Boy",
"Bonefish Grill",
"Boomarang Diner",
"Boston Pizza",
"Brewers Fayre",
"Brio Tuscan Grille",
"Brotzeit",
"Bubba Gump Shrimp Company",
"Buca di Beppo",
"Buffalo Grill",
"Buffalo Wild Wings",
"Buffalo Wings & Rings",
"Buffalo's Cafe",
"Burger Fuel",
"Byron Hamburgers",
"Cabalen",
"Cactus Club Cafe",
"Café Rouge",
"California Pizza Kitchen",
"Camille's Sidewalk Cafe",
"Cantina Mariachi",
"The Capital Grille",
"Carino's Italian",
"Carlos'n Charlie's",
"Carluccio's Ltd",
"Carrabba's Italian Grill",
"Carrows",
"Champps Americana",
"Charlie Brown's Fresh Grill",
"Cheba Hut",
"Cheddar's Scratch Kitchen",
"The Cheesecake Factory",
"Chevys Fresh Mex",
"Chi-Chi's",
"Chickie's & Pete's",
"Chili's",
"Chiquito",
"Chuck-A-Rama",
"Chuck E. Cheese's",
"Chuy's",
"Cicis",
"Claim Jumper",
"Coco's Bakery",
"Congo Grille",
"Cooper's Hawk Winery & Restaurants",
"Copeland's",
"Cora",
"Côte",
"Cotton Patch Café",
"The Counter",
"Crabby Joe's Tap & Grill",
"Cracker Barrel",
"Dallas BBQ",
"Dametra Cafe",
"Dave & Buster's",
"Del Frisco's Double Eagle Steak House",
"Dencio's",
"Denny's",
"Dick's Last Resort",
"Dickey's Barbecue Pit",
"Din Tai Fung",
"Dindigul Thalappakatti Restaurant",
"Dishoom",
"Dixie Chili and Deli",
"Dunn's",
"Earls",
"East Side Mario's",
"Eat'n Park",
"Eddie Rocket's",
"Eddie V's Prime Seafood",
"Ed's Easy Diner",
"El Fenix",
"El Torito",
"Elephant Bar",
"Famous Dave's",
"Fatz Cafe",
"Feng Sushi",
"Fleming's Prime Steakhouse & Wine Bar",
"Flunch",
"Fogo de Chão",
"Fox's Pizza Den",
"Franco Manca",
"Frankie & Benny's",
"Fresh to Order",
"Friendly's",
"Frisch's Big Boy",
"Garduño's",
"Gatti's Pizza",
"Gator's Dockside",
"Gerry's Grill",
"Giraffe World Kitchen",
"Golden Corral",
"Golden Nugget Pancake House",
"Gourmet Burger Kitchen",
"Graffiti Junktion",
"Grandy's",
"Ground Round",
"Guzman y Gomez",
"Haidilao",
"Happy Joe's",
"Happy's Pizza",
"Hard Rock Cafe",
"Harry Ramsden's",
"Harvester",
"Hash House a go go",
"Hippopotamus",
"Hog's Australia's Steakhouse",
"Hooters",
"HopCat",
"Hoss's Steak and Sea House",
"Houlihan's",
"Houston's Restaurant",
"Huddle House",
"HuHot Mongolian Grill",
"Hurricane Grill & Wings",
"Hwy 55 Burgers Shakes & Fries",
"IHOP",
"Islands Fine Burgers & Drinks",
"J. Alexander's",
"Jack Astor's Bar and Grill",
"Jensen's Bøfhus",
"Jerry's J-Boy Restaurants",
"Jim's Restaurants",
"Jimmy Buffett's Margaritaville",
"Jimmy's Restaurants",
"Jinya Ramen Bar",
"Joe's Crab Shack",
"Joey's Seafood Restaurants",
"Johnny Rockets",
"John's Incredible Pizza Company",
"The Keg",
"Kelseys Original Roadhouse",
"Ker's WingHouse Bar & Grill",
"Kings Family Restaurants",
"Kona Grill",
"La Porchetta",
"La Tasca",
"Landry's Seafood",
"Larkburger",
"Las Iguanas",
"Laughing Planet",
"Lawry's",
"Lazy Dog Restaurant & Bar",
"Lee Roy Selmon's",
"Lee's Famous Recipe Chicken",
"Legal Sea Foods",
"Little Anita's",
"Little Sheep Group",
"Loch Fyne Restaurants",
"Logan's Roadhouse",
"LongHorn Steakhouse",
"Luby's",
"Lucille's Smokehouse Bar-B-Que",
"Maggiano's Little Italy",
"Maid-Rite",
"Mandarin Restaurant",
"Mao",
"Marie Callender's",
"Marrybrown",
"Mary Brown's",
"Max & Erma's"]
