restaurant_names = ["Americas Incredible Pizza Company",
"Anchor Bar",
"Angus Steakhouse",
"Anjappar Chettinad Restaurant",
"Annalakshmi",
"Applebees",
"Arab Udupi",
"ASK Italian",
"Bahama Breeze",
"Bakers Square",
"Bar Louie Restaurants",
"Baton Rouge",
"Becks Prime",
"Beef OBradys",
"Beefeater",
"Belgo",
"Bella Italia",
"Benihana",
"Bennigans",
"Bertuccis",
"Bickfords",
"Big Boy",
"Bills",
"BJs Restaurants",
"Black Angus Steakhouse",
"Black-eyed Pea",
"Bob Evans Restaurants",
"Bobs Big Boy",
"Bonefish Grill",
"Boomarang Diner",
"Boston Pizza",
"Brewers Fayre",
"Brio Tuscan Grille",
"Brotzeit",
"Bubba Gump Shrimp Company",
"Buca di Beppo",
"Buffalo Grill",
"Buffalo Wild Wings",
"Buffalo Wings & Rings",
"Buffalos Cafe",
"Burger Fuel",
"Byron Hamburgers",
"Cabalen",
"Cactus Club Cafe",
"Café Rouge",
"California Pizza Kitchen",
"Camilles Sidewalk Cafe",
"Cantina Mariachi",
"The Capital Grille",
"Carinos Italian",
"Carlosn Charlies",
"Carluccios Ltd",
"Carrabbas Italian Grill",
"Carrows",
"Champps Americana",
"Charlie Browns Fresh Grill",
"Cheba Hut",
"Cheddars Scratch Kitchen",
"The Cheesecake Factory",
"Chevys Fresh Mex",
"Chi-Chis",
"Chickies & Petes",
"Chilis",
"Chiquito",
"Chuck-A-Rama",
"Chuck E Cheeses",
"Chuys",
"Cicis",
"Claim Jumper",
"Cocos Bakery",
"Congo Grille",
"Coopers Hawk Winery & Restaurants",
"Copelands",
"Cora",
"Cote",
"Cotton Patch Café",
"The Counter",
"Crabby Joes Tap & Grill",
"Cracker Barrel",
"Dallas BBQ",
"Dametra Cafe",
"Dave & Busters",
"Del Friscos Double Eagle Steak House",
"Dencios",
"Dennys",
"Dicks Last Resort",
"Dickeys Barbecue Pit",
"Din Tai Fung",
"Dindigul Thalappakatti Restaurant",
"Dishoom",
"Dixie Chili and Deli",
"Dunns",
"Earls",
"East Side Marios",
"Eatn Park",
"Eddie Rockets",
"Eddie Vs Prime Seafood",
"Eds Easy Diner",
"El Fenix",
"El Torito",
"Elephant Bar",
"Famous Daves",
"Fatz Cafe",
"Feng Sushi",
"Flemings Prime Steakhouse & Wine Bar",
"Flunch",
"Fogo de Chão",
"Foxs Pizza Den",
"Franco Manca",
"Frankie & Bennys",
"Fresh to Order",
"Friendlys",
"Frischs Big Boy",
"Garduños",
"Gattis Pizza",
"Gators Dockside",
"Gerrys Grill",
"Giraffe World Kitchen",
"Golden Corral",
"Golden Nugget Pancake House",
"Gourmet Burger Kitchen",
"Graffiti Junktion",
"Grandys",
"Ground Round",
"Guzman y Gomez",
"Haidilao",
"Happy Joes",
"Happys Pizza",
"Hard Rock Cafe",
"Harry Ramsdens",
"Harvester",
"Hash House a go go",
"Hippopotamus",
"Hogs Australias Steakhouse",
"Hooters",
"HopCat",
"Hosss Steak and Sea House",
"Houlihans",
"Houstons Restaurant",
"Huddle House",
"HuHot Mongolian Grill",
"Hurricane Grill & Wings",
"Hwy 55 Burgers Shakes & Fries",
"IHOP",
"Islands Fine Burgers & Drinks",
"J Alexanders",
"Jack Astors Bar and Grill",
"Jensens Bofhus",
"Jerrys J-Boy Restaurants",
"Jims Restaurants",
"Jimmy Buffetts Margaritaville",
"Jimmys Restaurants",
"Jinya Ramen Bar",
"Joes Crab Shack",
"Joeys Seafood Restaurants",
"Johnny Rockets",
"Johns Incredible Pizza Company",
"The Keg",
"Kelseys Original Roadhouse",
"Kers WingHouse Bar & Grill",
"Kings Family Restaurants",
"Kona Grill",
"La Porchetta",
"La Tasca",
"Landrys Seafood",
"Larkburger",
"Las Iguanas",
"Laughing Planet",
"Lawrys",
"Lazy Dog Restaurant & Bar",
"Lee Roy Selmons",
"Lees Famous Recipe Chicken",
"Legal Sea Foods",
"Little Anitas",
"Little Sheep Group",
"Loch Fyne Restaurants",
"Logans Roadhouse",
"LongHorn Steakhouse",
"Lubys",
"Lucilles Smokehouse Bar-B-Que",
"Maggianos Little Italy",
"Maid-Rite",
"Mandarin Restaurant",
"Mao",
"Marie Callenders",
"Marrybrown",
"Mary Browns",
"Max & Ermas"]
